/// Cross-validation tests: swisseph.dart vs pyswisseph (libaditya's engine).
///
/// libaditya: https://gitlab.com/ninthhouse/libaditya
///
/// Loads reference_data.json generated by generate_reference.py and compares
/// every value against swisseph.dart's FFI bindings. Both libraries call the
/// same Swiss Ephemeris C code, so results should match to floating-point
/// precision.
///
/// Run:
///   cd <swisseph.dart>
///   dart test test/libaditya-validation/cross_validation_test.dart
///
/// Regenerate reference data:
///   cd <libaditya-checkout>
///   uv run python <swisseph.dart>/test/libaditya-validation/generate_reference.py

import 'dart:convert';
import 'dart:io';

import 'package:test/test.dart';
import 'package:swisseph/swisseph.dart';

/// Tolerance for floating-point comparison.
///
/// Both libraries call the same C functions, so results should match exactly.
/// We allow 1e-8 for minor double-precision rounding differences between
/// Python's ctypes and Dart's dart:ffi marshalling.
const double _eps = 1e-8;

/// Looser tolerance for values that go through additional computation
/// (e.g., rise/set iterative solver, topocentric corrections).
const double _epsLoose = 1e-4;

late Map<String, dynamic> _ref;
late SwissEph _swe;

void main() {
  setUpAll(() {
    final file = File('test/libaditya-validation/reference_data.json');
    if (!file.existsSync()) {
      throw StateError(
        'reference_data.json not found. Generate it first:\n'
        '  cd <libaditya-checkout>\n'
        '  uv run python <swisseph.dart>/test/libaditya-validation/generate_reference.py',
      );
    }
    _ref = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    _swe = SwissEph.find();
  });

  tearDownAll(() {
    _swe.close();
  });

  // ── 1. Julian Day conversion ──────────────────────────────────────────

  group('julday', () {
    test('all date → JD conversions match pyswisseph', () {
      final entries = _ref['julday'] as List;
      for (final entry in entries) {
        final input = entry['input'];
        final expectedJd = (entry['jd'] as num).toDouble();
        final jd = _swe.julday(
          input['year'] as int,
          input['month'] as int,
          input['day'] as int,
          (input['hour'] as num).toDouble(),
        );
        expect(jd, closeTo(expectedJd, _eps),
            reason: 'julday(${input['year']}-${input['month']}-${input['day']} '
                '${input['hour']}h)');
      }
    });

    test('all JD → date roundtrips match pyswisseph', () {
      final entries = _ref['julday'] as List;
      for (final entry in entries) {
        final jd = (entry['jd'] as num).toDouble();
        final expected = entry['revjul'];
        final result = _swe.revjul(jd);
        expect(result.year, equals(expected['year']),
            reason: 'revjul($jd).year');
        expect(result.month, equals(expected['month']),
            reason: 'revjul($jd).month');
        expect(result.day, equals(expected['day']),
            reason: 'revjul($jd).day');
        expect(result.hour, closeTo((expected['hour'] as num).toDouble(), 1e-6),
            reason: 'revjul($jd).hour');
      }
    });
  });

  // ── 2. Planetary positions — Moshier (tropical) ──────────────────────

  group('planet positions (Moshier, tropical)', () {
    test('all 91 planet/date combinations match pyswisseph', () {
      final entries = _ref['planet_positions_moshier'] as List;
      var tested = 0;
      for (final entry in entries) {
        if (entry.containsKey('error')) continue;
        final jd = (entry['jd'] as num).toDouble();
        final body = entry['body'] as int;
        final flags = entry['flags'] as int;
        final name = entry['body_name'] as String;
        final date = entry['date'];

        CalcResult result;
        try {
          result = _swe.calcUt(jd, body, flags);
        } on SweException {
          fail('calcUt threw for $name at ${date['year']}-${date['month']}-${date['day']}');
          return; // unreachable
        }

        expect(result.longitude,
            closeTo((entry['longitude'] as num).toDouble(), _eps),
            reason: '$name lon at JD=$jd');
        expect(result.latitude,
            closeTo((entry['latitude'] as num).toDouble(), _eps),
            reason: '$name lat at JD=$jd');
        expect(result.distance,
            closeTo((entry['distance'] as num).toDouble(), _eps),
            reason: '$name dist at JD=$jd');
        expect(result.longitudeSpeed,
            closeTo((entry['longitude_speed'] as num).toDouble(), _eps),
            reason: '$name lon_speed at JD=$jd');
        expect(result.latitudeSpeed,
            closeTo((entry['latitude_speed'] as num).toDouble(), _eps),
            reason: '$name lat_speed at JD=$jd');
        expect(result.distanceSpeed,
            closeTo((entry['distance_speed'] as num).toDouble(), _eps),
            reason: '$name dist_speed at JD=$jd');
        tested++;
      }
      expect(tested, greaterThan(80),
          reason: 'Should test at least 80 planet/date combinations');
    });
  });

  // ── 3. Sidereal positions — multiple ayanamsas ────────────────────────

  group('sidereal positions', () {
    test('all 56 sidereal planet/ayanamsa combinations match', () {
      final entries = _ref['sidereal_positions'] as List;
      var tested = 0;
      for (final entry in entries) {
        final jd = (entry['jd'] as num).toDouble();
        final sidId = entry['ayanamsa_id'] as int;
        final sidName = entry['ayanamsa_name'] as String;
        final body = entry['body'] as int;
        final bodyName = entry['body_name'] as String;

        _swe.setSidMode(sidId);
        final result = _swe.calcUt(
          jd, body, seflgMoseph | seflgSpeed | seflgSidereal,
        );

        expect(result.longitude,
            closeTo((entry['longitude'] as num).toDouble(), _eps),
            reason: '$bodyName sidereal ($sidName) lon at JD=$jd');
        expect(result.latitude,
            closeTo((entry['latitude'] as num).toDouble(), _eps),
            reason: '$bodyName sidereal ($sidName) lat at JD=$jd');
        tested++;
      }
      expect(tested, equals(56));
    });
  });

  // ── 4. Ayanamsa values ────────────────────────────────────────────────

  group('ayanamsa values', () {
    test('all 98 ayanamsa/date combinations match pyswisseph', () {
      // "True" ayanamsas (True Citra, True Revati, True Pushya) use fixed star
      // positions internally and are sensitive to which ephemeris engine is
      // active. pyswisseph had SE files loaded; our Dart tests use Moshier.
      // Allow ~1e-4 for those; strict 1e-8 for the rest.
      // IDs that use fixed star positions internally:
      const trueAyanamsas = {27, 28, 29, 30, 35, 36};

      final entries = _ref['ayanamsa_values'] as List;
      var tested = 0;
      for (final entry in entries) {
        final jd = (entry['jd'] as num).toDouble();
        final sidId = entry['ayanamsa_id'] as int;
        final sidName = entry['ayanamsa_name'] as String;
        final expected = (entry['value'] as num).toDouble();

        _swe.setSidMode(sidId);
        final aya = _swe.getAyanamsaUt(jd);

        final tol = trueAyanamsas.contains(sidId) ? 1e-4 : _eps;
        expect(aya, closeTo(expected, tol),
            reason: '$sidName (id=$sidId) ayanamsa at JD=$jd');
        tested++;
      }
      expect(tested, equals(98));
    });
  });

  // ── 5. Ayanamsa names ────────────────────────────────────────────────

  group('ayanamsa names', () {
    test('all 14 ayanamsa names match pyswisseph', () {
      final entries = _ref['ayanamsa_names'] as List;
      for (final entry in entries) {
        final sidId = entry['id'] as int;
        final expected = entry['swe_name'] as String;
        final name = _swe.getAyanamsaName(sidId);
        expect(name, equals(expected),
            reason: 'ayanamsa name for id=$sidId');
      }
    });
  });

  // ── 6. House cusps — multiple systems × locations × dates ─────────────

  group('house cusps', () {
    test('all 154 house system/location/date combinations match', () {
      final entries = _ref['house_cusps'] as List;
      var tested = 0;
      for (final entry in entries) {
        if (entry.containsKey('error')) continue;

        final jd = (entry['jd'] as num).toDouble();
        final loc = entry['location'];
        final lat = (loc['lat'] as num).toDouble();
        final lon = (loc['lon'] as num).toDouble();
        final locName = loc['name'] as String;
        final hsysCode = entry['hsys_code'] as int;
        final hsysName = entry['hsys_name'] as String;
        final expectedCusps = (entry['cusps'] as List).cast<num>();
        final expectedAscmc = (entry['ascmc'] as List).cast<num>();

        final result = _swe.houses(jd, lat, lon, hsysCode);
        final label = '$hsysName at $locName, JD=$jd';

        // pyswisseph returns 12 cusps (0-indexed); our wrapper returns 13
        // (index 0 unused). Compare cusps[1..12] against pyswisseph[0..11].
        for (var i = 0; i < expectedCusps.length && i < 12; i++) {
          expect(result.cusps[i + 1],
              closeTo(expectedCusps[i].toDouble(), _eps),
              reason: '$label cusp ${i + 1}');
        }

        // ascmc: pyswisseph returns 8 values, our wrapper returns 10.
        // Compare the first 8.
        for (var i = 0; i < expectedAscmc.length && i < 8; i++) {
          expect(result.ascmc[i],
              closeTo(expectedAscmc[i].toDouble(), _eps),
              reason: '$label ascmc[$i]');
        }

        // Convenience getters
        expect(result.ascendant,
            closeTo(expectedAscmc[0].toDouble(), _eps),
            reason: '$label ascendant');
        expect(result.mc,
            closeTo(expectedAscmc[1].toDouble(), _eps),
            reason: '$label MC');
        expect(result.armc,
            closeTo(expectedAscmc[2].toDouble(), _eps),
            reason: '$label ARMC');
        expect(result.vertex,
            closeTo(expectedAscmc[3].toDouble(), _eps),
            reason: '$label vertex');

        tested++;
      }
      expect(tested, greaterThan(140),
          reason: 'Should test at least 140 house combinations');
    });
  });

  // ── 7. House system names ─────────────────────────────────────────────

  group('house names', () {
    test('all 11 house system names match pyswisseph', () {
      final entries = _ref['house_names'] as List;
      for (final entry in entries) {
        final code = entry['code'] as int;
        final expected = entry['swe_name'] as String;
        final name = _swe.houseName(code);
        expect(name, equals(expected),
            reason: 'house name for ${entry['char']}');
      }
    });
  });

  // ── 8. Planet names ───────────────────────────────────────────────────

  group('planet names', () {
    test('all 13 planet names match pyswisseph', () {
      final entries = _ref['planet_names'] as List;
      for (final entry in entries) {
        final pid = entry['id'] as int;
        final expected = entry['swe_name'] as String;
        final name = _swe.getPlanetName(pid);
        expect(name, equals(expected),
            reason: 'planet name for id=$pid');
      }
    });
  });

  // ── 9. Rise/set times ────────────────────────────────────────────────

  group('rise/set times', () {
    test('all 32 rise/set events match pyswisseph', () {
      final entries = _ref['rise_set'] as List;
      var tested = 0;
      for (final entry in entries) {
        if (entry.containsKey('error')) continue;

        final jd = (entry['jd'] as num).toDouble();
        final body = entry['body'] as int;
        final bodyName = entry['body_name'] as String;
        final eventName = entry['event'] as String;
        final flag = entry['flag'] as int;
        final loc = entry['location'];
        final lat = (loc['lat'] as num).toDouble();
        final lon = (loc['lon'] as num).toDouble();
        final alt = (loc['alt'] as num).toDouble();
        final locName = loc['name'] as String;
        final expectedJd = (entry['transit_jd'] as num).toDouble();

        final result = _swe.riseTrans(
          jd, body,
          epheflag: seflgMoseph,
          rsmi: flag,
          geolon: lon,
          geolat: lat,
          geoalt: alt,
          atpress: 1013.25,
          attemp: 15.0,
        );

        expect(result.transitTime, closeTo(expectedJd, _epsLoose),
            reason: '$bodyName $eventName at $locName, JD=$jd');
        tested++;
      }
      expect(tested, greaterThan(25),
          reason: 'Should test at least 25 rise/set events');
    });
  });

  // ── 10. Degree normalization ──────────────────────────────────────────

  group('degnorm', () {
    test('all 15 normalization cases match pyswisseph', () {
      final entries = _ref['degnorm'] as List;
      for (final entry in entries) {
        final input = (entry['input'] as num).toDouble();
        final expected = (entry['output'] as num).toDouble();
        final result = _swe.degnorm(input);
        expect(result, closeTo(expected, _eps),
            reason: 'degnorm($input)');
      }
    });
  });

  // ── 11. Topocentric positions ─────────────────────────────────────────

  group('topocentric positions', () {
    test('all 8 topocentric Sun/Moon positions match', () {
      final entries = _ref['topocentric'] as List;
      var tested = 0;
      for (final entry in entries) {
        final jd = (entry['jd'] as num).toDouble();
        final body = entry['body'] as int;
        final bodyName = entry['body_name'] as String;
        final loc = entry['location'];
        final lat = (loc['lat'] as num).toDouble();
        final lon = (loc['lon'] as num).toDouble();
        final alt = (loc['alt'] as num).toDouble();
        final locName = loc['name'] as String;

        _swe.setTopo(lon, lat, alt);
        final result = _swe.calcUt(
          jd, body, seflgMoseph | seflgSpeed | seflgTopoctr,
        );

        expect(result.longitude,
            closeTo((entry['longitude'] as num).toDouble(), _eps),
            reason: '$bodyName topocentric lon at $locName');
        expect(result.latitude,
            closeTo((entry['latitude'] as num).toDouble(), _eps),
            reason: '$bodyName topocentric lat at $locName');
        expect(result.distance,
            closeTo((entry['distance'] as num).toDouble(), _eps),
            reason: '$bodyName topocentric dist at $locName');
        tested++;
      }
      expect(tested, equals(8));
    });
  });

  // ── 12. Equatorial coordinates ────────────────────────────────────────

  group('equatorial coordinates', () {
    test('all 7 classical planet RA/Dec values match', () {
      final entries = _ref['equatorial'] as List;
      for (final entry in entries) {
        final jd = (entry['jd'] as num).toDouble();
        final body = entry['body'] as int;
        final bodyName = entry['body_name'] as String;

        final result = _swe.calcUt(
          jd, body, seflgMoseph | seflgSpeed | seflgEquatorial,
        );

        // In equatorial mode, longitude=RA, latitude=Dec
        expect(result.longitude,
            closeTo((entry['right_ascension'] as num).toDouble(), _eps),
            reason: '$bodyName RA');
        expect(result.latitude,
            closeTo((entry['declination'] as num).toDouble(), _eps),
            reason: '$bodyName Dec');
        expect(result.distance,
            closeTo((entry['distance'] as num).toDouble(), _eps),
            reason: '$bodyName equatorial dist');
      }
    });
  });

  // ── 13. Summary ───────────────────────────────────────────────────────

  group('coverage summary', () {
    test('reference data has expected section counts', () {
      expect((_ref['julday'] as List).length, equals(7));
      expect((_ref['planet_positions_moshier'] as List).length, equals(91));
      expect((_ref['sidereal_positions'] as List).length, equals(56));
      expect((_ref['ayanamsa_values'] as List).length, equals(98));
      expect((_ref['ayanamsa_names'] as List).length, equals(14));
      expect((_ref['house_cusps'] as List).length, equals(154));
      expect((_ref['house_names'] as List).length, equals(11));
      expect((_ref['planet_names'] as List).length, equals(13));
      expect((_ref['rise_set'] as List).length, equals(32));
      expect((_ref['degnorm'] as List).length, equals(15));
      expect((_ref['topocentric'] as List).length, equals(8));
      expect((_ref['equatorial'] as List).length, equals(7));
    });
  });
}
